spring:
  application:
    name: cars

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: api-car
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.wesleypi.cars.queue # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
topic:
  create-car: topic-create-car

external-api:
  user: ${USER_CREDENTIAL}
  pass: ${PASS_CREDENTIAL}
  base-url: http://api-test.bhut.com.br:3000/api/
  car-uri: /v1/carro
  refresh-token-uri: /v1/autenticacao/renova-token
  token-uri: /v1/autenticacao/token

